Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-2a
      ImageId: ami-0e84e211558a022c0
      InstanceType: t2.micro
      KeyName: deploymac
      securitygroupids: 
        - sg-0732ccb264701420b
      subnetid: subnet-02d54ed551c722d21
      Tags:
        - 
          Key: Name
          Value: MyCFNEC2

