Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          sources: 
            C:\temp: "s3://codedeploy-salsman-apetguru/apetgurumod.zip"
    Properties: 
      AvailabilityZone: us-east-2a
      ImageId: ami-0a83d9223efc49d62
      InstanceType: t2.micro
      KeyName: codedeployTest
      SecurityGroupIds:
        - sg-0732ccb264701420b
      SubnetId: subnet-02d54ed551c722d21
      IamInstanceProfile: ec2codedeployuser   
      Tags:
        - 
          Key: Name
          Value: MyCFNWindowsEC2

