Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Metadata: 
      AWS::CloudFormation::Init: 
        config: 
          sources: 
            C:\Temp: "https://codedeploy-salsman-apetguru.s3.us-east-2.amazonaws.com/apetgurumod.zip"
    Properties: 
      AvailabilityZone: us-east-2a
      ImageId: ami-0a83d9223efc49d62
      InstanceType: t2.micro
      KeyName: codedeployTest
      SecurityGroupIds:
        - sg-0732ccb264701420b
      SubnetId: subnet-02d54ed551c722d21
      IamInstanceProfile: ec2codedeployuser
      Tags:
        - 
          Key: Name
          Value: MyCFNWindowsEC2
      UserData: 
        Fn::Base64: |
          - ''
          - - "<script>\n"
            - '"C:\Program Files (x86)\Amazon\cfn-bootstrap\cfn-init.exe\" -v -s '
            - !Ref 'AWS::StackName'
            - "\n"
            - "</script>\n"
